apiVersion: skaffold/v1beta15
kind: Config
metadata:
  name: graphql-test-skaffold
build:
  local: {}
  tagPolicy:
    sha256: {}
  artifacts:
    - image: graphql-test-ui
      context: services/ui
      sync:
        infer:
          - "**/*.html"
          - "**/*.css"
          - "**/*.ts"
          - "**/*.tsx"
          - "package.json"
      docker:
        dockerfile: Dockerfile
    - image: graphql-test-middlware
      context: services/middleware
      sync:
        infer:
          - "**/*.ts"
          - "**/*.js"
          - "*.js"
          - "package.json"
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - deployments/ui/deployment.yaml
      - deployments/middleware/deployment.yaml
