apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: middleware
  template:
    metadata:
      labels:
        component: middleware
    spec:
      initContainers:
        - name: init-database
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until nslookup database-service; do echo waiting for database-service; sleep 2; done;",
            ]
      containers:
        - name: middleware
          image: choem/graphql-test-middleware:latest
          ports:
            - containerPort: 4000
