apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: middleware
  template:
    metadata:
      labels:
        component: middleware
    spec:
      initContainers:
        - name: init-database
          image: mysql/mysql-server:8.0.16
          command:
            [
              "sh",
              "-c",
              "while ! mysqladmin ping -h database-service --silent; do sleep 1; done",
            ]
      containers:
        - name: middleware
          image: choem/graphql-test-middleware:latest
          ports:
            - containerPort: 4000
