#!/bin/bash

set -e # Exit if the script encounters an error

# Ensure that images that are build exist within the minikube docker context
eval $(minikube docker-env)

# Build services or specific service
services=($(ls -d services/* | cut -f2 -d'/'))

for service in "${services[@]}"
do
  echo "Building image for ${service}"
  source "build_image.sh" $service
done